parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    _instanceof:
        App\Database\Structure\StructureInterface:
            tags: ['database.structure_tag']
        App\Database\Executor\ExecutorInterface:
            tags: ['database.executor_tag']


    App\State\PagePostProcessor:
        bind:
            $decorated: '@api_platform.doctrine.orm.state.persist_processor'

    App\State\PagePutProcessor:
        bind:
            $decorated: '@api_platform.doctrine.orm.state.persist_processor'

    App\EventListener\PagePostPersistListener:
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postPersist'
                entity: 'App\Entity\Page'



    App\EventListener\PagePostUpdateListener:
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postUpdate'
                entity: 'App\Entity\Page'
