parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    _instanceof:
        App\DatabaseSwitch\infrastructure\Structure\StructureInterface:
            tags: ['database.structure_tag']
        App\DatabaseSwitch\infrastructure\Executor\ExecutorInterface:
            tags: ['database.executor_tag']


    App\SandBox\Application\StateProcessor\PagePostProcessor:
        bind:
            $decorated: '@api_platform.doctrine.orm.state.persist_processor'

    App\SandBox\Application\StateProcessor\PagePutProcessor:
        bind:
            $decorated: '@api_platform.doctrine.orm.state.persist_processor'

    App\SandBox\Domain\Events\PagePostUpdateListener:
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postUpdate'
                entity: 'App\SandBox\Domain\Entity\Page'
