version: "3.8"
services:
  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: unless-stopped
    ports:
      - 7777:8080
    networks:
      - app-network
